# NOT FOR PRODUCTION USE!!!

version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: wellenplan
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: wellenplan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
